name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ vars.API_URL }}
          NEXT_PUBLIC_SITE_URL: ${{ vars.SITE_URL }}
          NEXT_PUBLIC_ENV: production

      - name: Upload out directory
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4